name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
    BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup cross compiler
        run: sudo apt-get install -y gcc-arm-none-eabi cmake make ninja-build
      - name: check compiler
        run: |
          which gcc-arm-none-eabi || echo "gcc-arm-none-eabi not found"
          which arm-none-eabi-gcc || echo "arm-none-eabi-gcc not found"
      - name: configure
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: build
        run: cmake --build build
